# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rack"
gem "sinatra"
gem "sinatra-reloader"
gem "pg" , '0.9.0'
